"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Header = exports.FormContainer = exports.Container = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
exports.Container = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  width: 100%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n\n  .noForms {\n    margin-top: 30px;\n    width: 68%;\n    box-shadow: 0px 1px 3px rgba(0,0,0,.1);\n    background-color: #fff;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex-direction: column;\n    padding: 40px;\n\n    h1 {\n      color: #222222;\n      font-size: 18px;\n    }\n\n    p {\n      color: #888888;\n      font-size: 1rem;\n    }\n  }\n\n  .recentForms {\n    width: 68%;\n    display: flex;\n    overflow-x: auto;\n\n    a {\n      text-decoration: none;\n      margin: 3px;\n    }\n\n    ::-webkit-scrollbar {\n    width: 10px;\n    height: 8px;\n    }\n    ::-webkit-scrollbar-thumb {\n    background: #e2e2e2;\n    border-radius: 7px;\n    }\n    ::-webkit-scrollbar-thumb:hover{\n    background: #D6D6D6;\n    cursor: all-scroll;\n    }\n    ::-webkit-scrollbar-track{\n    border-radius: 9px;\n    box-shadow: inset -30px -30px 0px #f1f1f1;\n    }\n  }\n  \n  @media screen and (max-width: 600px) {\n    .recentForms {\n      width: 80%;\n      display: flex;\n      align-items: center;\n      overflow: auto;\n      height: 100vh;\n      padding-bottom: 360px;\n\n      ::-webkit-scrollbar {\n        display: none;\n      }\n    }\n  }\n"], ["\n  width: 100%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n\n  .noForms {\n    margin-top: 30px;\n    width: 68%;\n    box-shadow: 0px 1px 3px rgba(0,0,0,.1);\n    background-color: #fff;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex-direction: column;\n    padding: 40px;\n\n    h1 {\n      color: #222222;\n      font-size: 18px;\n    }\n\n    p {\n      color: #888888;\n      font-size: 1rem;\n    }\n  }\n\n  .recentForms {\n    width: 68%;\n    display: flex;\n    overflow-x: auto;\n\n    a {\n      text-decoration: none;\n      margin: 3px;\n    }\n\n    ::-webkit-scrollbar {\n    width: 10px;\n    height: 8px;\n    }\n    ::-webkit-scrollbar-thumb {\n    background: #e2e2e2;\n    border-radius: 7px;\n    }\n    ::-webkit-scrollbar-thumb:hover{\n    background: #D6D6D6;\n    cursor: all-scroll;\n    }\n    ::-webkit-scrollbar-track{\n    border-radius: 9px;\n    box-shadow: inset -30px -30px 0px #f1f1f1;\n    }\n  }\n  \n  @media screen and (max-width: 600px) {\n    .recentForms {\n      width: 80%;\n      display: flex;\n      align-items: center;\n      overflow: auto;\n      height: 100vh;\n      padding-bottom: 360px;\n\n      ::-webkit-scrollbar {\n        display: none;\n      }\n    }\n  }\n"])));
exports.FormContainer = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  border: 1px solid #e2e2e2;\n  cursor: pointer;\n  transition: 300ms ease all;\n  width: 198px;\n  display: flex;align-items: center;justify-content: center;flex-direction: column;\n\n  &:hover {\n    border: 1px solid #8430ce;\n  }\n\n  .gray {\n    width: 196px;\n    background-color: #e2e2e2;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    padding: 40px 14px;\n\n    img {\n      height: 100px;\n    }\n  }\n\n  .content {\n    padding: 10px 14px;\n\n    .title {\n      color: #464a4e;\n      font-size: 14px;\n      margin-left: 2px;\n      margin-bottom: 2px;\n\n      width: 160px;\n      white-space: nowrap;\n      overflow: hidden;\n      text-overflow: ellipsis;\n    }\n\n    .infos {\n      display: flex;\n      align-items: center;\n      justify-content: space-between;\n\n      p {\n        font-size: 12px;\n        color: #80868b;\n      }\n\n      .list {\n        color: #8430ce;\n      }\n\n      .dots {\n        color: #5f6368;\n      }\n    }\n  }\n"], ["\n  border: 1px solid #e2e2e2;\n  cursor: pointer;\n  transition: 300ms ease all;\n  width: 198px;\n  display: flex;align-items: center;justify-content: center;flex-direction: column;\n\n  &:hover {\n    border: 1px solid #8430ce;\n  }\n\n  .gray {\n    width: 196px;\n    background-color: #e2e2e2;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    padding: 40px 14px;\n\n    img {\n      height: 100px;\n    }\n  }\n\n  .content {\n    padding: 10px 14px;\n\n    .title {\n      color: #464a4e;\n      font-size: 14px;\n      margin-left: 2px;\n      margin-bottom: 2px;\n\n      width: 160px;\n      white-space: nowrap;\n      overflow: hidden;\n      text-overflow: ellipsis;\n    }\n\n    .infos {\n      display: flex;\n      align-items: center;\n      justify-content: space-between;\n\n      p {\n        font-size: 12px;\n        color: #80868b;\n      }\n\n      .list {\n        color: #8430ce;\n      }\n\n      .dots {\n        color: #5f6368;\n      }\n    }\n  }\n"])));
exports.Header = styled_components_1.default.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  width: 68%;\n  padding: 6px 8px 6px 2px;\n  display: flex;\n  align-items: center;\n  \n  h1 {\n    margin-right: auto;\n    color: #202124;\n    font-size: 1rem;\n  }\n\n  .right {\n    display: flex;\n    \n    .button {\n      display: flex;\n\n      button {\n        border-radius: 50%;\n        background-color: transparent;\n        border: none;\n        height: 38px;\n        margin-left: 6px;\n        width: 38px;\n        cursor: pointer;\n        transition: all 200ms ease;\n\n        &:active {\n          transform: scale(0.9)\n        }\n\n        &:hover {\n          background-color: #f3f3f3;\n        }\n\n        &:hover > .popup {\n          opacity: 1;\n        }\n      }\n    }\n  }\n\n  @media screen and (max-width: 600px) {\n    width: 80%;\n\n    .right {\n      position: relative;\n      left: 14px;\n    }\n  }\n"], ["\n  width: 68%;\n  padding: 6px 8px 6px 2px;\n  display: flex;\n  align-items: center;\n  \n  h1 {\n    margin-right: auto;\n    color: #202124;\n    font-size: 1rem;\n  }\n\n  .right {\n    display: flex;\n    \n    .button {\n      display: flex;\n\n      button {\n        border-radius: 50%;\n        background-color: transparent;\n        border: none;\n        height: 38px;\n        margin-left: 6px;\n        width: 38px;\n        cursor: pointer;\n        transition: all 200ms ease;\n\n        &:active {\n          transform: scale(0.9)\n        }\n\n        &:hover {\n          background-color: #f3f3f3;\n        }\n\n        &:hover > .popup {\n          opacity: 1;\n        }\n      }\n    }\n  }\n\n  @media screen and (max-width: 600px) {\n    width: 80%;\n\n    .right {\n      position: relative;\n      left: 14px;\n    }\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3;
